### ISSUE TITLE
Accessing rejected components

### ISSUE THREAD

**Issue by sebsau** [dnacombo/SASICA#8]
Hi,

this is not strictly an error issue but I wasn't able to find a solution anywhere else. So I'd be very grateful for some help.

How can I access the ICs that SASICA selected for rejection? In my preprocessing script, I use the following line

`[EEG] = SASICA(EEG,'MARA_enable',0,'FASTER_enable',0,'FASTER_blinkchanname','No channel','ADJUST_enable',1,'chancorr_enable',1,'chancorr_channames','E14','chancorr_corthresh','auto 4','EOGcorr_enable',1,'EOGcorr_Heogchannames','E125','EOGcorr_corthreshH','auto 4','EOGcorr_Veogchannames','E8','EOGcorr_corthreshV','auto 4','resvar_enable',0,'resvar_thresh',15,'SNR_enable',0,'SNR_snrcut',1,'SNR_snrBL',[-Inf 0] ,'SNR_snrPOI',[0 Inf] ,'trialfoc_enable',1,'trialfoc_focaltrialout','auto','focalcomp_enable',1,'focalcomp_focalICAout','auto','autocorr_enable',1,'autocorr_autocorrint',20,'autocorr_dropautocorr','auto','opts_noplot',0,'opts_nocompute',0,'opts_FontSize',14);`

When I use the GUI, I can just click on reject and then later reject the selected components in the EEGLAB GUI. But when just running a script, I can't find out how to access the components that were selected for rejection. In the function, I read that this should be in `com` but this is always empty for me.

Thanks a lot for any help!
-- Sebastian

**Comment by kurokirasama** [comment]
what is the answer?

**Comment by dnacombo** [comment]
Hi,
When running from the command line, I recommend using eeg_SASICA instead of SASICA. It uses the same syntax but should be more robust.

In the output EEG structure, there is a .reject field.
EEG.reject.gcompreject points to all rejected components (this is EEGLAB convention).
EEG.reject.SASICA.icarejautocorr points to components rejected via autocorrelation. other methods follow same pattern.

**Comment by kurokirasama** [comment]
thanks!
